### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#64]
If I had the power to make this a Milestone in GitHub, I would 😉
this is the list of things that I think are agreed upon as "things to do for the v1 release"
inspired by https://github.com/spenserblack/actions-wiki/discussions/44

- [x] use `path` instead of `wiki-directory` #52 
- [ ] have `repository` input support bare `user/repo` slugs without github.com prefix
- [x] have a `dry-run` input to not do push #51 
- [ ] mirror `token: ${{ secrets.GITHUB_TOKEN }}` default token input format from other actions #59

**Comment by spenserblack** [comment]
>If I had the power to make this a Milestone in GitHub, I would

Done :wink:

Although sometimes it's nice to have a meta-issue for some discussion, so let's leave this open 🙂

**Comment by jcbhmr** [comment]
some other ideas for v1 things:
1. #57 -- discussion is still open; i assume its still up for debate
2. #17 (i know i said id never bring it up again)

**Comment by jcbhmr** [comment]
@spenserblack would you pin this issue pretty pls? 🥺
